<?php

namespace App\HttpController\Api;

use EasySwoole\Core\Http\AbstractInterface\Controller;

/**
 * 基础类库
 * Class Base
 * @package App\HttpController\Api
 */
class Base extends Controller
{
    function index()
    {
        $data = [
            'id' =>1,
            'name'=>"base index"
        ];
        return $this->writeJson(200,'ok', $data);
    }

    /**
     * 设置权限相关的
     * @param $action
     * @return bool|null
     */
    public function onRequest($action):?bool
    {
        return true;
    }

    /**
     * 处理异常
     * @param \Throwable $throwable
     * @param $actionName
     */
    public function onException(\Throwable $throwable, $actionName): void
    {
        $this->writeJson(400, "请求不合法");
//        parent::onException($throwable, $actionName); // TODO: Change the autogenerated stub
    }


}